server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: authorization-service
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true 
    serialization: 
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
  security:
    user:
      name: admin
      password: admin

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fms
    username: root
    password: root
    
  jpa:
    #database-platform: org.hibernate.dialect.MySQL5Dialect
    #database: MYSQL
    openInView: false
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.region.factory_class: org.hibernate.cache.internal.NoCachingRegionFactory
      hibernate.jdbc.lob.non_contextual_creation: true

  data:
    jpa:
      repositories.enabled: true
    rest:
      default-media-type: application/json
        
  hateoas:
    use-hal-as-default-json-media-type: false

logging:
  level:
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    com.fms: DEBUG
  file: authorization.log
  pattern:
    console: "%d{dd-MMM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
    
employee-service:
  ribbon:
    
    # Eureka vipAddress of the target service
    DeploymentContextBasedVipAddresses: employee-service

    #listOfServers: localhost:${SERVER.PORT}
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList

    # Interval to refresh the server list from the source (ms)
    ServerListRefreshInterval: 30000
events-service:
  ribbon:
    
    # Eureka vipAddress of the target service
    DeploymentContextBasedVipAddresses: events-service

    #listOfServers: localhost:${SERVER.PORT}
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList

    # Interval to refresh the server list from the source (ms)
    ServerListRefreshInterval: 30000

   
zuul:
  host:
    connect-timeout-millis: 50000000
    socket-timeout-millis: 5000000
  ignored-services: '*'
  routes:
    employee-service:
      sensitive-headers: '*'
      path: /employees-api/**
      service-id: employee-service
      strip-prefix: false
    events-service:
      sensitive-headers: '*'
      path: /events-api/**
      service-id: events-service
      strip-prefix: false
  add-proxy-headers: false
  strip-prefix: false
ribbon:
  ReadTimeout: 60000      
employee:
  service:
    name : employee-service