version: '2'

services:

  fms-ui:
    container_name: fms-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '80:80'