server:
  port: 8761
   
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    secure-port-enabled: false
    
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${server.port}/eureka/
