server:
  port: 8002
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
    secure-port-enabled: false

management:
  endpoint:
    service-registry:
      enabled: true

spring:
  application:
    name: events-service
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true 
    serialization: 
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://3.20.216.200:3306/fms
   username: kesav
   password: kesav
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: MYSQL
    openInView: false
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.region.factory_class: org.hibernate.cache.internal.NoCachingRegionFactory
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate:
        format_sql:    true
        jdbc:
          batch_size:  10
        order_inserts: true
        order_updates: true
  data:
    jpa:
      repositories.enabled: true
    rest:
      default-media-type: application/json
        
  batch:
    job:
      enabled: false
    initialize-schema: always
  hateoas:
    use-hal-as-default-json-media-type: false

logging:
  level:
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    org.hibernate: error
    com.fms: trace
    org.springframework.batch: trace
  file: event-service.log
  pattern:
    console: "%d{dd-MMM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"